name: SQL Test
on: [push]
jobs:
  check-sql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        # Cette partie force GitHub à attendre que MySQL réponde
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Run all SQL files
        run: |
          for file in *.sql; do
            echo "Running $file..."
            mysql -h 127.0.0.1 -u root < "$file"
          done